import pygame


FPS = 30
WINDOWWIDTH = 1000 #1280
WINDOWHEIGHT = 750 #1024

#Map values
BOXSIZE = 30
MAPROWS = 100 #140 #number of cells in the underlying map
MAPCOLS = 100 #140
MAPWIDTH = MAPCOLS * BOXSIZE
MAPHEIGHT = MAPROWS * BOXSIZE

#Viewscreen values
LEFTMARGIN = 0
TOPMARGIN = 0
VIEWWIDTH = 3 * WINDOWWIDTH / 4
VIEWHEIGHT = WINDOWHEIGHT
FOVCOLS = VIEWWIDTH / BOXSIZE
FOVROWS = VIEWHEIGHT / BOXSIZE
VIEWRECT = pygame.Rect((LEFTMARGIN, TOPMARGIN, VIEWWIDTH, VIEWHEIGHT))


#Main menu values
MAINMENU_LEFT = WINDOWWIDTH - WINDOWWIDTH / 4
MAINMENU_TOP = 0
MAINMENU_WIDTH = WINDOWWIDTH / 4
MAINMENU_HEIGHT = WINDOWHEIGHT
MAINMENU_RECT = pygame.Rect((MAINMENU_LEFT, MAINMENU_TOP, MAINMENU_WIDTH, MAINMENU_HEIGHT))

#Shape menu values
SHAPEMENU_LEFT = WINDOWWIDTH - MAINMENU_WIDTH
SHAPEMENU_TOP = 0
SHAPEMENU_WIDTH = MAINMENU_WIDTH
SHAPEMENU_HEIGHT = MAINMENU_HEIGHT / 3
SHAPEMENU_RECT = pygame.Rect((SHAPEMENU_LEFT, SHAPEMENU_TOP, SHAPEMENU_WIDTH, SHAPEMENU_HEIGHT))

#Color menu values
COLORMENU_LEFT = WINDOWWIDTH - MAINMENU_WIDTH
COLORMENU_TOP = SHAPEMENU_HEIGHT
COLORMENU_WIDTH = MAINMENU_WIDTH
COLORMENU_HEIGHT = MAINMENU_HEIGHT / 3
COLORMENU_RECT = pygame.Rect((COLORMENU_LEFT, COLORMENU_TOP, COLORMENU_WIDTH, COLORMENU_HEIGHT))

#DrawingMenu values
DRAWINGMENU_LEFT = WINDOWWIDTH - MAINMENU_WIDTH
DRAWINGMENU_TOP = 0
DRAWINGMENU_WIDTH = MAINMENU_WIDTH
DRAWINGMENU_HEIGHT = SHAPEMENU_HEIGHT+COLORMENU_HEIGHT
DRAWINGMENU_RECT = pygame.Rect((DRAWINGMENU_LEFT, DRAWINGMENU_TOP, DRAWINGMENU_WIDTH, 
								DRAWINGMENU_HEIGHT))

#CharacterCreator menu values
CHARACTERCREATOR_LEFT = WINDOWWIDTH - MAINMENU_WIDTH 
CHARACTERCREATOR_TOP = 0
CHARACTERCREATOR_WIDTH = MAINMENU_WIDTH
CHARACTERCREATOR_HEIGHT = MAINMENU_HEIGHT / 3
CHARACTERCREATOR_RECT = pygame.Rect((CHARACTERCREATOR_LEFT, CHARACTERCREATOR_TOP,
									CHARACTERCREATOR_WIDTH, CHARACTERCREATOR_HEIGHT))

#SaveMenu values
SAVEMENU_LEFT = WINDOWWIDTH/4
SAVEMENU_TOP = WINDOWHEIGHT/4
SAVEMENU_WIDTH = WINDOWWIDTH/2
SAVEMENU_HEIGHT = WINDOWHEIGHT/2
SAVEMENU_RECT = pygame.Rect((SAVEMENU_LEFT, SAVEMENU_TOP, SAVEMENU_WIDTH, SAVEMENU_HEIGHT))

#LoadMenuSuper values
LOADMENU_LEFT = WINDOWWIDTH/4
LOADMENU_TOP = WINDOWHEIGHT/4
LOADMENU_WIDTH = WINDOWWIDTH/2
LOADMENU_HEIGHT = WINDOWHEIGHT/2
LOADMENU_RECT = pygame.Rect((LOADMENU_LEFT, LOADMENU_TOP, LOADMENU_WIDTH, LOADMENU_HEIGHT))

#About values
ABOUT_LEFT = WINDOWWIDTH/4
ABOUT_TOP = WINDOWHEIGHT/4
ABOUT_WIDTH = WINDOWWIDTH/2
ABOUT_HEIGHT = WINDOWHEIGHT/2
ABOUT_RECT = pygame.Rect((ABOUT_LEFT, ABOUT_TOP, ABOUT_WIDTH, ABOUT_HEIGHT))
